clone:
  depth: full
pipelines:
  branches:
    master:
      - step:
          name: Deploy to production
          deployment: production
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master -f